# Compile stage
FROM golang:alpine AS build-env

ENV CGO_ENABLED=0 \
    GO111MODULE=on

RUN apk add --no-cache git

WORKDIR /build
COPY . .

RUN go mod download
# The -gcflags "all=-N -l" flag helps us get a better debug experience
RUN go build -gcflags "all=-N -l" -o main

# Compile Delve
WORKDIR /go/src
RUN go get github.com/go-delve/delve/cmd/dlv

# Final stage
FROM alpine:3.7
# Port 8080 belongs to our application, 40000 belongs to Delve
EXPOSE 8080 40000
WORKDIR /
# Allow delve to run on Alpine based containers.
RUN apk add --no-cache libc6-compat

COPY --from=build-env /build /
COPY --from=build-env /go/bin/dlv /

# Run delve
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/main"]