version: '3'

services:
  app:
    container_name: debug-remote
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "40000:40000" # debugging endpoint
      - "3000:3000" # application endpoint
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE