version: '3'

services:
  app:
    container_name: go-debug-remote
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "40000:40000" # debugging endpoint
      - "3000:3000" # application endpoint
#    command:
#      - dlv exec --listen=:40000 --accept-multiclient --headless=true --api-version=2 --log /app
#      - reflex -c /reflex.conf
#      - runner -c /runner.conf
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE